server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# CORS
app.cors.allowed-origins=http://localhost:4200,     https://shirke-ems-production.up.railway.app, http://103.168.19.63:84

# JWT
schoolapp.jwtSecret=secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
schoolapp.jwtExpirationMs=86400000

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nalawadeaditya844@gmail.com
spring.mail.password=hloqddbbkcvsaaua
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true